### ISSUE TITLE
P0: ErrorBoundary catches component load failure after OrderBook merge

### ISSUE THREAD

**Issue by gxcsoccer** [gxcsoccer/AlphaArena#64]
## Bug Description

After merging PR #63 (OrderBook component), the deployed application shows an ErrorBoundary error: "组件加载失败" (Component load failure).

## Impact

- **All 25 UI acceptance tests blocked**
- Application not functional for users
- Sprint 3 cannot complete

## Evidence

- Test report: `.virtucorp/test-reports/sprint3-acceptance-rerun.md`
- Deployed URL: https://alphaarena-1010tcrkv-gxcsoccer-s-team.vercel.app
- ErrorBoundary is catching a runtime error

## Investigation Checklist

- [ ] Check browser console for JavaScript errors
- [ ] Verify Supabase environment variables are configured correctly
- [ ] Check RealtimeClient initialization
- [ ] Review OrderBook component imports and dependencies
- [ ] Check for any TypeScript compilation errors that were ignored
- [ ] Verify the component doesn't throw on initial render

## Priority

P0 - Complete application failure, blocks Sprint 3
